# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: api

generate:
  echo-server: true
  models: true
  strict-server: true
output: ../../internal/generated/server.gen.go
